# A Quick Introduction to Numerical Data Maipulation with Python

NumPy stands for numerical Python. it's the backbone of all kinds of scientific and numerical computing in Python.
And since machine learning is all about turning data into numbers and then
fuguring out the patterns, NumPy often comes into play.


## Why NumPy?
You can do numerical calculations using pure Python. In the begining you might think Pythin us fast but once your data gets large, you'll start to notice slow downs. One of the main reasons you use NumPy is because it's fast. Behind the scenes the has been optimized to run using C. Which is closer to machine code 

In [1]:
""" 
0. Importing NumPy
acronym np 
"""

import numpy as np 
print(np.__version__)

2.4.6


In [16]:
"""
1. DataTypes and attributes  

Note: Important to remeber the main tye of NumPy is ndarray, even seemingly different kinds of arrays are still ndarray's.
This meanss and operation you do on one array will work on another.

Note the keyword for this is actually the dimension represents the level of nesting.
"""

#1-dimensional array, also referred to as a vector 

a1 = np.array([1,2,3])

a2 = np.array([[1,2,3], [4,5,6.5]])

a3 = np.array([
  
    [[1,2.2,3],
    [6,7,7],
    [2.1,3.4,3.5]],
     [[1,2.2,3],
    [6,7,7],
    [2.1,3.4,3.5]]

],

)

In [17]:


""" 
Understanding the shape :

The shape just tells you how the array is structured.
for a one dimension array since there is only one level of nesting it tells you exactly how many columns they need (3,)
for a two dimension array since there is two level of nesting the nesting tells you exactly how many rows and columns (2,3)

now for 3 dimension array since there is 3 level of nesting you can look at it as a how many  block

"""
print(a1.shape)
print(a2.shape)
print(a3.shape)


(3,)
(2, 3)
(2, 3, 3)


In [18]:
"""ndim just tells you the number of dimension"""

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [19]:
"""dtype 
bool < int < float < complex < str < object the moment one of the upper type is present into an array 1D 
it gets assign that type  and i gues sit compares each 1D arrays,then each 2D arrays and within that process takes the upcast
"""

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
float64


In [14]:
"""
the size, the total number of elements in total.
"""
print(a1.size)
print(a2.size)
print(a3.size)

3
6
18


In [22]:
"""
The type of any np array  is .ndarray
"""
print(type(a1))
print(type(a2))
print(type(a3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [30]:
"""
Creating arrays 
Same logic for np.zeros(structure taking a nple)
1.  create any type of ndarray
2. np.ones creates arrays of onesand tqaes a tuple where you tell it the structure the shape 

so lets say i want a 2D array well the shape is (2,3) , 2 nested structure i nthis case it represents the 2 rows and 3 columns
but lets say you wanted 3 nested structure well it would be (2,3,3) 3 nested structure but you have to understand at this level it is recursvily depdent of the 
previous structures meaning that the 2,3,3 just means two blocks that 2 blocks that contains a 2D array in other words 2 blocks of 2D arrays so 

for fourth dimension it would be give me 2,2,3,3 give me 2 of 3D structure as you see it is recursively dependent on the previous structure.
"""

print(np.array([1,2,3]))
print(np.ones((2,2,3,3)))
# You can change the datatype with .astype(), sicne the default type is float type(np.ones((2,3))) wil loutput float64 wrong it wil loutput ndarray it was a trap
# np.ones((2,3)).dtype that would be float64, same logic for np.zeros 
np.ones.astype(int)

[1 2 3]
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
